### ISSUE TITLE
Occasional 0 byte files are written

### ISSUE THREAD

**Issue by nickkonidaris** [sdss/lvmscp#10]
Occasionally, 0-byte files are written. Not sure why this happens or how to provide more debugging info.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/3804541/193966066-355ec496-547a-4784-8b59-2128f7e1604a.png">

It looks like lvmscp crashed either during readout, or soon thereafter (I haven't looked at log files, so I can't tell the specific order).

**Comment by albireox** [comment]
I haven't seen this in a long while, so I'm going to assume it's fixed now and reopening if it reappears.
