### ISSUE TITLE
actor click option --config removed

### ISSUE THREAD

**Issue by wasndas** [sdss/lvmscp#4]
Is there a reason that it was removed in the latest push [here](https://github.com/sdss/lvmscp/commit/a137583d4a6783df85b85fd2a800be3f7bc874ab#diff-8b58cf266284d2124023a801cf4f0d0b7fa5ce9e57462b06f229d28b25ed447fL21) ?

**Comment by albireox** [comment]
I think I removed because it was actually never used in the code. I reverted it.

**Comment by wasndas** [comment]
Sure, less is more.

Thanks for adding promptly the rmq option, it is now way more elegant, than creating a new config file  with sed replacing the rabbitmq host. In principal you could remove the --config again ,-)
